# Other
export GIT_EDITOR=vi
export SVN_EDITOR=vi
export EDITOR=vi
export WINE_PREFIX=$HOME/.wine

# Bash
export PATH=$HOME/bin:$PATH
source $HOME/.bash_aliases
source $HOME/.bash_functions
if [ -e $HOME/.ssh/agent ]; then
  source $HOME/.ssh/agent
fi

# For playing videos through ssh
export DISPLAY=:0

# Colorize prompt and directories
eval $(dircolors -b $HOME/.dircolors)
promptcolors

# Show directory in urxvt title bar
case "$TERM" in
  xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
  ;;
    *)
  ;;
esac
