# Set keyboard delay/rate
xset r rate 275 30

# Turn off the beep
xset -b

# Swap capslock and control
setxkbmap -option ctrl:swapcaps

# Set mouse acceleration
xset m 2

ssh-agent | sed -e '3d' > ~/.ssh/agent
