# Set keyboard delay/rate
xset r rate 275 30
# Swap capslock and control
setxkbmap -option ctrl:swapcaps
# New Xorg auto-sets this: group(alt_shift_toggle), which freaks out wmii
setxkbmap -symbols 'pc+us+inet(evdev)+level3(ralt_switch)+ctrl(swapcaps)+compose(lwin)'

ssh-agent | sed -e '3d' > ~/.ssh/agent


